version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: proffeo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - proffeo-network
        
  proffeo-api:
    build:
      context: .
      dockerfile: src/Proffeo.Api/Dockerfile
    ports:
      - "5050:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=proffeo;Username=user;Password=password;
    depends_on:
      - postgres
    networks:
      - proffeo-network
      
networks:
  proffeo-network:
    driver: bridge
    
volumes:
  postgres_data: